# Site settings
title: Yoyo's Blog
#SEOTitle: YOYOµÄ²©¿Í | BY Sophia
#header-img: img/post-bg-swift.jpg
email: 653781720@qq.com
description: "Keep moving and keep thinking!"
keyword: "JAVA,Git,Web Crawler"
url: "http://Sophia99.github.io/MyBlog"          # your host, for absolute URL
#baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
baseurl: /MyBlog
github_repo: "https://sophia99.github.io/MyBlog" # you code repository






